
resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/nitram509/concourse-java-maven-test-prj.git
      branch: master
  - name: time
    type: time
    source:
      interval: 60s


jobs:
  - name: maven package
    plan:
    - get: git-repo
      trigger: true
    - task: maven-package
      privileged: true
      file: git-repo/pipeline/maven-package.yml

  - name: rename file
    plan:
    - aggregate:
      - get: git-repo
        passed: [maven package]
      - get: time
    - task: rename-file
      file: git-repo/pipeline/rename-file.yml