
resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/nitram509/concourse-java-maven-test-prj.git
      branch: master

jobs:
  - name: maven
    plan:
    - get: git-repo
      trigger: true
    - task: maven-package
      privileged: true
      file: git-repo/pipeline/maven-package.yml